# -*- coding: utf-8 -*-
"""3-stacks-queues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiXm1vSS-w3vA3QK9NJvtTFcKY7Y_VWD

# Stacks with Arrays
"""

class StackArr:
    def __init__(self, size):
        self.array_size = size
        self.top = -1
        self.array = [None] * size

    def push(self, value):
        # If stack is full, expand the size
        if self.top == self.array_size - 1:
            self.array_size *= 2
            self.array.extend([None] * self.array_size)
            print("Array expanded to size:", self.array_size)

        self.top += 1
        self.array[self.top] = value

    def pop(self):
        if self.top == -1:
            return None  # Stack is empty
        value = self.array[self.top]
        self.top -= 1
        return value

    def is_empty(self):
        return self.top == -1

    def peek(self):
        if self.top == -1:
            return None
        return self.array[self.top]

"""## Reverse String with a Stack"""

def reverse_string(input_string): # HELLO = 5
    # practice
    stack = StackArr(len(input_string)) # size parameter
    for char in input_string:
      stack.push(char)

    reversed_str = ''
    while not stack.is_empty():
      reversed_str += stack.pop()

    return reversed_str

print(reverse_string("Tyson Vs. Paul was a money grab!!"))

"""## Undo Feature in Text Editor"""

def text_editor_simulation(commands):
    # practice
    text_stack = StackArr(10)
    undo_stack = StackArr(10)

    for command in commands:
      if command.startswith("type "):
        char = command.split()[1]
        text_stack.push(char)
      elif command == "undo":
        undo_stack.push(text_stack.pop())
      elif command == "redo":
        if not undo_stack.is_empty():
          text_stack.push(undo_stack.pop())
          # inside IF
        # inside ELIF
      # inside FOR
    # outside FOR
    # Result string
    result = ""
    while not text_stack.is_empty():
      result = text_stack.pop() + result

    return result

commands = [
    "type A", "type B", "type Q", "type U", "undo", "undo", "type C"
]
print(text_editor_simulation(commands))

"""# Stacks with Linked Lists"""

class LinkedListNode:
    def __init__(self, value):
        self.value = value
        self.next = None

class StackLL:
    def __init__(self):
        self.head = None

    def push(self, value):
        new_node = LinkedListNode(value)
        new_node.next = self.head
        self.head = new_node

    def pop(self):
        if self.head is None:
            return None  # Stack is empty
        value = self.head.value
        self.head = self.head.next
        return value

    def is_empty(self):
        return self.head is None

    def peek(self):
        if self.head is None:
            return None
        return self.head.value

"""## Check for Balanced Parentheses"""

def is_balanced(expression):
    # practice
    stack = StackLL()
    matching_brackets = {
        ')': '(',
        '}': '{',
        ']': '['
    }
    for char in expression:
      if char in "({[":
        stack.push(char)
      elif char in ")}]":
        top = stack.pop()
        if top != matching_brackets[char]: # )
          return False

    return stack.is_empty()

print(is_balanced("(Hello{nice[to(meet)you]})")) # True
print(is_balanced("(Hello{nice[to(meet)you])")) # False

"""## Browser Navigation"""

def browser_navigation(urls):
    # practice
    back_stack = StackLL() # previously visited history
    forward_stack = StackLL() # after "back" history
    current_page = None

    for action in urls:
      if action.startswith("visit "):
        if current_page:
          back_stack.push(current_page)
        current_page = action.split()[1] # visit google.com
        # Clear the forward stack because we visited a new page
        while not forward_stack.is_empty():
          forward_stack.pop()
      elif action == "back" and not back_stack.is_empty():
        forward_stack.push(current_page)
        current_page = back_stack.pop()
      elif action == "forward" and not forward_stack.is_empty():
        back_stack.push(current_page)
        current_page = forward_stack.pop()

      print("Current page: ", current_page) # auto \n

commands = [
    "visit wikipedia.org",
    "visit youtube.com",
    "visit amazon.com",
    "back",
    "back",
    "forward",
    "visit yts.mx",
    "visit ft.com",
    "visit coinmarketcap.com",
    "back",
    "forward"
]
browser_navigation(commands)

"""## Explanation

1. **Array-based Stack:**
  - Uses a list with dynamic resizing (`self.array.extend()`).
  - Offers `push()`, `pop()`, `is_empty()`, and `peek()` methods.
2. **Linked List-based Stack:**
  - Implements stack using `LinkedListNode` to manage nodes.
  - No need to resize, as memory is allocated dynamically.
3. **Examples:**
  - **Reversing a String:** Uses a stack to reverse characters.
  - **Balanced Parentheses:** Checks matching brackets using a stack.
  - **Text Editor Undo/Redo:** Manages typing and undo/redo commands.
  - **Browser Navigation:** Mimics a web browser back/forward navigation.

Feel free to try out and modify these examples!

---
# Queues
"""

class LinkedListNode:
    def __init__(self, value):
        self.value = value
        self.next = None

class Queue:
    def __init__(self):
        self.front = None
        self.back = None

    def enqueue(self, value):
        new_node = LinkedListNode(value)
        if self.back is None:  # Queue is empty
            self.front = new_node
            self.back = new_node
        else:
            self.back.next = new_node
            self.back = new_node

    def dequeue(self):
        if self.front is None:  # Queue is empty
            return None
        value = self.front.value
        self.front = self.front.next
        if self.front is None:  # If queue becomes empty
            self.back = None
        return value

    def is_empty(self):
        return self.front is None

    def peek(self):
        if self.front is None:
            return None
        return self.front.value

"""## Simulate a Ticket Counter"""

def simulate_coffee_counter(customers):
    # practice
    q = Queue()
    for customer in customers:
      q.enqueue(customer)

    print("Serving all customers:")
    while not q.is_empty():
      print("Serving: ", q.dequeue())

simulate_coffee_counter([
    "Aaron", "Umid", "Umar", "Ammar", "Elon", "Jake", "Logan"
])

"""## Hot Potato Game (Circle Elimination)"""

def hot_potato(players, rounds):
    #practice

"""## Printer Job Queue Sim"""

def printer_job_queue(jobs):
    # practice

"""## Customer Service Help Desk"""

class HelpDesk:
    # practice

"""## Call Center"""

import random
import time

def call_center_simulation(calls):
    # practice

"""## Explanation

1. **Queue Implementation:**
  - Uses a linked list with front pointing to the first element and back pointing to the last.
  - `enqueue()`: Adds a new element to the back of the queue.
  - `dequeue()`: Removes and returns the element from the front.
  - `is_empty()`: Checks if the queue is empty.
  - `peek()`: Returns the front element without removing it.
2. **Examples:**
  - **Ticket Counter:** Serves customers in the order they arrive.
  - **Hot Potato Game:** Eliminates players in a circular manner until one remains.
  - **Printer Job Queue:** Simulates jobs being processed in the order they are added.
  - **Help Desk Queue:** Handles customer service requests.
  - **Call Center:** Simulates a call center handling incoming calls.

These scenarios illustrate real-world applications of queues, showing how they manage tasks in a "first-in, first-out" (FIFO) manner.
"""

