# -*- coding: utf-8 -*-
"""4-best

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vn72EvO3bYeNhzSkoKLbvzQoJ6tGp3gV
"""

class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
        self.parent = None

class BinarySearchTree:
    def __init__(self):
        self.root = None

    def find_value(self, current, target):
        if current is None:
            return None
        if current.value == target:
            return current
        if target < current.value:
            return self.find_value(current.left, target)
        else:
            return self.find_value(current.right, target)

    def find_value_itr(self, root, target):
        current = root
        while current is not None and current.value != target:
            if target < current.value:
                current = current.left
            else:
                current = current.right
        return current

    def find_tree_node(self, target):
        if self.root is None:
            return None
        return self.find_value(self.root, target)

    def insert_tree_node(self, new_value):
        if self.root is None:
            self.root = TreeNode(new_value)
        else:
            self.insert_node(self.root, new_value)

    def insert_node(self, current, new_value):
        if new_value == current.value:
            return  # Skip inserting duplicates
        if new_value < current.value:
            if current.left is not None:
                self.insert_node(current.left, new_value)
            else:
                current.left = TreeNode(new_value)
                current.left.parent = current
        else:
            if current.right is not None:
                self.insert_node(current.right, new_value)
            else:
                current.right = TreeNode(new_value)
                current.right.parent = current

    def remove_tree_node(self, node):
        if node is None:
          return

        # Case A: Leaf Node
        if node.left is None and node.right is None:
          if node.parent is None: # it's the root!
            self.root = None
          elif node.parent.left == node:
            node.parent.left = None
          else:
            node.parent.right = None

        # Case B: One Child
        elif node.left is None or node.right is None:
          # Condition ? True : False
          child = node.left if node.left is not None else node.right
          child.parent = node.parent
          if node.parent is None: # it's the root!
            self.root = child
          elif node.parent.left == node:
            node.parent.left = child
          else:
            node.parent.right = child

        # Case C: Two children
        else:
          successor = self.get_min_value_node(node.right)
          self.remove_tree_node(successor)
          successor.parent = node.parent

          if node.parent is None: # it's the root!
            self.root = successor
          elif node.parent.left == node:
            node.parent.left = successor
          else:
            node.parent.right = successor

          successor.left = node.left
          successor.right = node.right

          if node.left is not None:
            node.left.parent = successor
          if node.right is not None:
            node.right.parent = successor


    def get_min_value_node(self, node, max = False, debug = False):
        if debug:
          print("Debugging!")
        current = node
        if max:
          while current.right is not None:
              current = current.right
        else:
          while current.left is not None:
              current = current.left
        return current

    def remove_value(self, target):
        node = self.find_tree_node(target)
        self.remove_tree_node(node)

    def print_tree(self):
        levels = []
        self._print_tree_helper(self.root, 0, levels)
        for depth, nodes in enumerate(levels):
          print(f"Level {depth}: " + " ".join(map(str, nodes)) + "\n")

    def _print_tree_helper(self, node, depth, levels):
        if node is None:
          return
        if (len(levels) == depth):
          levels.append([])
        levels[depth].append(node.value)
        self._print_tree_helper(node.left, depth + 1, levels)
        self._print_tree_helper(node.right, depth + 1, levels)

bst = BinarySearchTree()
bst.insert_tree_node(50) # Root: 50
bst.insert_tree_node(30) # Left: 30
bst.insert_tree_node(70) # Right: 70
bst.insert_tree_node(20)
bst.insert_tree_node(40)
bst.insert_tree_node(60)
bst.insert_tree_node(80)
bst.insert_tree_node(10)
bst.insert_tree_node(100)
bst.insert_tree_node(90)
bst.insert_tree_node(0)

print("BST after inserts:")
bst.print_tree()

print("Finding 20:", bst.find_tree_node(20))
print("Finding 55:", bst.find_tree_node(55))
print("Finding 0:", bst.find_tree_node(0))

bst.remove_value(0) # Remove leaf
print("Tree after removing 0:")
bst.print_tree()

bst.remove_value(100) # Remove node with one child
print("Tree after removing 100:")
bst.print_tree()

bst.remove_value(50) # Remove root node
print("Tree after removing 50:")
bst.print_tree()

min_node = bst.get_min_value_node(bst.root)
print("Min value in Tree:", min_node.value)

max_node = bst.get_min_value_node(bst.root, 1, 1)
print("Max value in Tree:", max_node.value)