# -*- coding: utf-8 -*-
"""travel korea

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YG5xG1Vuuw7ESpgoOwWVpb_22Du2Ln3V
"""

import heapq
import networkx as nx
import matplotlib.pyplot as plt

landmarks = {
    "jeonju": {
        "daejeon":62,
        "gwangju":80,
        "jinju":116
    },
    "jinju":{"jeonju": 116,"busan" :86 },
    "gwangju":{"jeonju": 80, "daejeon" : 142},
    "busan": {
        "jinju":86,
        "ulsan":46,
        "jeju":299
    },
    "ulsan": {"daejeon": 197, "busan": 46},
    "jeju": {"busan": 299},
    "daejeon": {
        "jeonju":62,
        "ulsan" :197,
        "gwangju" : 142
    }
  }

# BFS (shortest path)
def bfs(graph, start ,end):
  visited = set()
  queue = [(start,[start])]
  while queue :
    current, path = queue.pop(0)
    if current == end:
      return path
    if current not in visited:
      visited.add(current)
      for neighbor in graph[current]:
        queue.append((neighbor,path + [neighbor]))
  return None

# Dijkstra's (shortest travel time)
def dijkstra(graph, start):
  min_heap = [(0, start)]
  times ={landmark: float('inf') for landmark in graph}
  times[start] = 0
  while min_heap:
    current_time, current_landmark = heapq.heappop(min_heap)
    for neighbor , time in graph[current_landmark].items():
      new_time = current_time + time
      if new_time < times[neighbor]:
        times[neighbor] = new_time
        heapq.heappush(min_heap,(new_time,neighbor))
  return times

# Examples
print("BFS from jeonju to jeju:")
print(bfs(landmarks,"jeonju", "jeju"))

print("\nDijkstra's from jeonju:")
print(dijkstra (landmarks, "jeonju"))

# Visualize Graph
def visualize_graph(graph):
    G = nx.Graph()
    for landmark, connections in graph.items():
        for neighbor, weight in connections.items():
             G.add_edge(landmark, neighbor,weight=weight)
    pos = nx.spring_layout(G)
    nx.draw(G, pos, with_labels=True, node_size=2000, font_size=10)
    edge_labels = nx.get_edge_attributes(G,'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)
    plt.title('Travel Itineray Graph')
    plt.show()

#Visualization
visualize_graph(landmarks)